# Generated by Django 5.1.6 on 2025-02-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_booksmodel_image_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksmodel',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='audio_book',
            field=models.URLField(blank=True, verbose_name='Ссылка на аудиокнигу'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='genre',
            field=models.CharField(choices=[('COMEDY', 'Comedy'), ('SCIENCE', 'Science'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('FANTASY', 'Fantasy')], default='FANTASY', max_length=10, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='image',
            field=models.ImageField(upload_to='books/', verbose_name='Загрузите фото'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='pages',
            field=models.PositiveIntegerField(default=250, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='price',
            field=models.PositiveIntegerField(default=200, verbose_name='Цена книги'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='review',
            name='choice_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.booksmodel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('🌟', '1 звезда'), ('🌟🌟', '2 звезды'), ('🌟🌟🌟', '3 звезды'), ('🌟🌟🌟🌟', '4 звезды'), ('🌟🌟🌟🌟🌟', '5 звезд')], default='🌟🌟🌟', max_length=10),
        ),
    ]
